server:
  port: 8082
spring:
  r2dbc:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: 1234
    database: "ReactiveApp"
    liquibase:
      enabled: true
  application:
    name: "requests"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        queues:
          stateChange: "loan-application-state-change"
          capacityRequest: "loan-application-capacity-request"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8082"
postgresql:
  host: "localhost"
  port: 5432
  database: "ReactiveApp"
  username: "postgres"
  password: 1234
logging:
  level:
    org.springframework.data.r2dbc: "DEBUG"
    org.springframework.data.repository: "DEBUG"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8082"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
jwt:
  secret: "LaClaveSuperSecreta7611201250MiClaveSuperSecreta"

