version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgresapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ReactiveApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  loacrediya:
    build:
      context: ../applications/app-service
      dockerfile: ../../deployment/Dockerfile
    container_name: loacrediya-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ReactiveApp
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: